### ISSUE TITLE
TemplateNotFound

### ISSUE THREAD

**Issue by hostsistemas** [katomaro/katomart#1]
Após executar katomart.py consigo entrar na home pelo navegador: http://127.0.0.1:6102/home, 
mas nas outras páginas: [Configurações] [ Gerenciar Contas] [ Gerenciar Cursos] [ LOGs] [ Suporte] apresentam o erro abaixo:

TemplateNotFound
jinja2.exceptions.TemplateNotFound: settings.html

Traceback (most recent call last)
File "C:\Program Files\Python312\Lib\site-packages\flask\app.py", line 1478, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\app.py", line 1458, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\katomart\katomart.py", line 34, in settings
return render_template('settings.html')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\templating.py", line 151, in render_template
template = app.jinja_env.get_or_select_template(template_name_or_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
return self._load_template(name, globals)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\jinja2\loaders.py", line 125, in load
source, filename, uptodate = self.get_source(environment, name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\templating.py", line 65, in get_source
return self._get_source_fast(environment, template)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python312\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
raise TemplateNotFound(template)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateNotFound: settings.html
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by katomaro** [comment]
Isso está explicado [nesta seção do readme](https://github.com/katomaro/katomart?tab=readme-ov-file#este-reposit%C3%B3rio-funciona-mesmo), em resumo, o código completo com todas as páginas ainda não foi publicado. Provavelmente publico a versão da hotmart funcional essa semana, assim que eu acabar outro projeto que estou fazendo em paralelo com este.

**Comment by hostsistemas** [comment]
alguma previsão?

**Comment by drummerpva** [comment]
@katomaro Salve, desde já obrigado pelo trampo, será que sai esses mês ainda?

**Comment by katomaro** [comment]
> @katomaro Salve, desde já obrigado pelo trampo, será que sai esses mês ainda?

Hoje foi minha última consulta neuropsicológica, então provavelmente vou fazer sem estilizar essa madrugada pra hotmart, aí o @felipe-adeildo dps customiza

**Comment by katomaro** [comment]
@hostsistemas Por curiosidade, qual a sua plataforma alvo?  

@drummerpva preciso que o felipe estilize as páginas (principalmente o termo legal) para eu poder revisar todo o código interinamente e começar a liberar os downloaders todos com algumas coisas. Ainda falta adicionar algumas configurações na página, mas vou esperar ele estilizar para eu adicionar, coisa de thread, automatização, expiry, etc, não é tão "primordial" como as coisas que coloquei de opção essa madrugada. E para a página não ficar muito extensa, acredito que ele vai separar por seção colapsável, não sei.  

Certeza que sai hotmart, kiwify, green, gran, alpa, estratégia, e alguns outros de uma vez, só preciso ver todo o jurídico mesmo.

**Comment by katomaro** [comment]
Estado da aplicação: Tem como selecionar uma plataforma e adicionar as credenciais na db. Tenho que fazer a função para remover a a conta se a pessoa quiser, melhorar o back para utlizar de joins e entregar mais dados para a página de contas, mas falta apenas uma página para o aplicativo estar 'completo', que é a que gerencia download de cursos.  
Tenho melhorias para fazer na página de configurações também, porém, primeiro algo funcional nesse modelo novo né? Hotmart em muito, muito, muito, breve (possivelmente próxima madrugada ou hoje de noite)
