### ISSUE TITLE
suporte

### ISSUE THREAD

**Issue by Christianssantana** [katomaro/katomart#16]
Olá Kato, tudo certo?
Quando for possível, conseguiria adicionar suporte para a plataforma AstronMembers?
Obrigado

**Comment by katomaro** [comment]
Duplicado na requisição número #6 , você deve manifestar seu interesse nesta plataforma no interesse já manifestado por outro usuário ao invés de abrir uma nova solicitação. Comente na issue referida nessa mensagem para ela ganhar força, lembrando que implementações com votos de sponsors tomam precedência as demais.
