### ISSUE TITLE
Botão Iniciar Downloads não habilita

### ISSUE THREAD

**Issue by joeltonconte** [katomaro/katomart#18]
Segui todos os passos, mas o botão para iniciar os downloads na plataforma hotmart não habilita. Todos os vídeos aparecem, são selecionados, estão disponíveis, mas não consigo baixar.

**Comment by toti18** [comment]
Infelizmente estou com o mesmo problema... o projeto consegue acessar a minha conta na plataforma Hotmart, consegue acessar e listar todos os cursos, porém, ao selecionar qualquer um dos que eu gostaria de baixar, o botão Download não habilita para poder baixar (ele fica em cinza) e, deste modo, não conseguimos fazer o download das aulas :-(

**Comment by felipe-adeildo** [comment]
@toti18 e @joeltonconte, boa noite.

O script ainda não está pronto, o botão de downlaod não ativa pq ainda não é pra ativar kkkkkk.

Previsão pra sair o script? Depdende da minha saúde, e tempo meu e do kato.

To morrendo essa semana, fiz poucos commits, preciso entregar uma parte visual e funcional do frontend e aí o downloader em si vai ser implementado.

ou seja, aguardem.


Nota: Boa parte do que eu falei (fora meu estado de saúde) está naquele textão enorme, se vcs lessem o que está escrito, saberiam que o bot ainda não está funcionando.

**Comment by katomaro** [comment]
Olha, o botão agora habilita....para te avisar que está em progresso. Novamente, peço que sempre leia o aviso na página principal, mas agora o download deve vir rápido. Seremos justos, se apareceu todas as aulas para você, você já tem uma garantia que só não está funcionando por causa que a gente ainda não finalizou, queremos entregar algo bem feito, não algo porco mas que funciona, que tal se tornar sponsor deste projeto que vem evoluindo tem uns 3 anos? As vezes, faz sair mais rápido, vai saber.
