### ISSUE TITLE
Adicionar suporte para hotmart empresas

### ISSUE THREAD

**Issue by doiiido** [katomaro/katomart#22]
Olá, boa tarde!
Estive usando outro projeto CLI que baixa os cursos da Hotmart (https://github.com/benedictus79/Hotm4rtei) mas esbarrei em um problema com um curso com URLs bem diferentes dos outros:
A url base do curso é completamente diferente do esperado no programa:
`https://hotmart.com/pt-br/club/<NomeDaEmpresa>/products/<idDoCurso>/content/<idDoVideo>`
A URL dos videos também é diferente:
`https://vod-akm.play.hotmart.com/video/`
Enquanto trabalho nessa issue do projeto de lá vim aqui recomendar que considerem isso no projeto de vocês, a correção rápida que fiz naquele (Issue [32](https://github.com/benedictus79/Hotm4rtei/issues/32)) foi uma breaking change devido à estrutura diferente das tags do html e será um trabalho de umas boas horas permitir o funcionamento nas duas estruturas. 
Recomendo considerarem isso desde o início no projeto de vocês para evitar retrabalho posterior.

Atenciosamente,
Lincoln.

**Comment by katomaro** [comment]
"O projeto de vocês" é anterior ao projeto dele. Não é legal citar projetos secundários em repositórios autorais, ainda mais quando o autor menciona diversos casos de plágio, venda do FOSS e afins, como eu fiz no aviso.HTML. A Hotmart vive mudando quando eu atualizo script, então é de se esperar, por isso que foi criada a tela de Aviso na home, para quando eles alterarem algo suspeito. Lá você pode estar lidando com iniciantes, aqui não.
