### ISSUE TITLE
Possibilidade de acoplamento entre projetos

### ISSUE THREAD

**Issue by doiiido** [katomaro/katomart#23]
Venho sugerir um acoplamento deste projeto com o [Hotm4rtei](https://github.com/benedictus79/Hotm4rtei) para acelerar o desenvolvimento dos dois e adicionar neste a possiblidade de ter uma CLI para o usuário avançado e/ou por acesso SSH.
O outro projeto está pendente ainda de uma GUI e acreditos que o escopo de ambos se completam.

[Issue com a sugestão lá](https://github.com/benedictus79/Hotm4rtei/issues/33)

Atenciosamente,
Lincoln.

**Comment by katomaro** [comment]
O projeto mencionado tem relação com grupos de pirataria, portanto sendo ilegal e passível de denúncia (dos grupos). Leia o AVISO.html que eu citei. Além disso, o Katomart teve seu lançamento anterior ao supracitado, e foi o primeiro script público para download de plataforma, eu fazia scripts avulsos e agora unifiquei eles em uma interface web. A sugestão de CLI continua ok, mas SSH não é interessante pois o destino de uso do programa é para o detentor da licença, de consumo usar ele em vps já é uma quebra pois passa pela mão de terceiros, a grosso modo. E não, eles não se completam, um tem base totalmente legal, o outro surgiu depois e é vinculado a grupos de pirataria como citei.

**Comment by felipe-adeildo** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
