### ISSUE TITLE
Listagem de Cursos

### ISSUE THREAD

**Issue by JulianoRossi3l** [katomaro/katomart#32]
Eu adicionei 2 contas, e ele reconheceu as 2 corretamente, mas só esta fazendo a listagem da primeira conta. Quando eu seleciono a segunda conta, ele mostra apenas os cursos que foram carregados da primeira conta. Infelizmente não há uma terceira conta, para que eu consiga testar. Como faz para limpar o cache, para eu adicionar as contas novamente, e corrigir esse bug?

**Comment by katomaro** [comment]
Não existe bem um cache, você pode remover cada conta individualmente no painel, mas realmente parece ser um bug. Vou verificar agora se tem a ver com o front (dados enviados) ou com o back (manipulação de objetos), logo retorno e atribuo a pessoa correta ao problema apresentado.

**Comment by katomaro** [comment]
Testado aqui do meu lado com 4 contas, não foi possível replicar o comportamento mencionado. Eu adicionei o seguinte código na seguinte linha do servidor https://github.com/katomaro/katomart/blob/d582d46d1770bde474ff9c358053495ee33628e2/katomart.py#L286  

```python
print(f'[DEBUG]', '*'*50)
print(f'[DEBUG] Account ID: {account_id}, Platform ID: {platform_id}')
print(f'[DEBUG] Json postado: {request.get_json()}')
print(f'[DEBUG]', '*'*50)
```

O output produzido (dado recebido pelo front) foi o esperado e a listagem na aba cursos foi a correta:
```
[DEBUG] **************************************************
[DEBUG] Account ID: 3, Platform ID: 1
[DEBUG] Json postado: {'account_id': 3, 'platform_id': 1}
[DEBUG] **************************************************
```

Sendo assim, não foi possível que eu reproduzisse o comportamento aqui. Você está na última atualização? Por favor detalhe os passos tomados para que eu tente reproduzir este comportamento novamente.  

Passos que **EU** tomei:
1. Clonei o repositório para ter a versão disponibilizada à público e não a versão em desenvolvimento ativo
2. Aceitei os termos, fui na aba **Contas** e adicionei duas contas, lembrei que tinha esquecido de adicionar o código no back para constatar um possível erro de lógica, encerrei o aplicativo e fechei a aba do navegador
3. Adicionei o código, iniciei o aplicativo novamente executando `python katomart.py`, fui na aba **Contas** e adicionei outras duas contas
4. Testei inicializar sessão em cada e foi tudo normal.

Possível erro que você possa ter cometido: Na aba contas, selecionar uma conta diferente e esquecer de apertar o botão "Inicializar conta" antes de ir para a aba **Cursos**, aí ele vai listar os produtos da conta inicializada anteriormente mesmo, é assim que ele funcional, te permite operar apenas uma conta por vez por motivos de segurança.

**Comment by katomaro** [comment]
Fechada devido inatividade.
