### ISSUE TITLE
Tenho 9 Cursos mas Só Aparecem 6 Cursos

### ISSUE THREAD

**Issue by kevenasley** [katomaro/katomart#36]
Tenho um curso que comprei, está no período de garantia e ele não aparece para baixar.

**Comment by katomaro** [comment]
Curioso, não me lembro de ter implementado nenhum bloqueio. Olhando no terminal, aparece o nome dele na lista? (Não compartilhe a lista em si).

**Comment by katomaro** [comment]
@Daniel-Gouvea Se ainda necessitar, me chama no Telegram.
