### ISSUE TITLE
Erro simples de digitação

### ISSUE THREAD

**Issue by Daniel-Gouvea** [katomaro/katomart#40]
Apenas um erro simples, mas, pelo porte do projeto, acho que vale a pena comentar.
Ao iniciar uma conta (só testei pela plataforma Hotmart), o Katomart iniciar a busca pelos cursos e, nesse momento, ele mostra "_Cerregando cursos... (caso tenha muitos cursos, isso pode demorar um pouco)_". 
O correto seria "_Carregando cursos..._".

Espero ter ajudado.

**Comment by katomaro** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk, vou corrigir agora
