### ISSUE TITLE
Erro: 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by Osdrix** [katomaro/katomart#45]
Erro ao baixar o arquivo, tentativa 2 de 5. Erro: 504 Server Error: Gateway Time-out for url: https://vod-akm.play.hotmart.com/video/....

**Comment by katomaro** [comment]
Troquei o download do meu manual para o ytdlp, experimenta agora.

**Comment by Osdrix** [comment]
Erro ao baixar o arquivo, tentativa 2 de 5. Erro: 504 Server Error: Gateway Time-out for url: https://vod-akm.play.hotmart.com/video/zQZPOBDzLw/hls/zQ*******

Nível: Error

Dados Sensíveis?: Sim

----hotmart ----

**Comment by katomaro** [comment]
@Osdrix Você tem que baixar a atualização. Se tiver o git instalado no pc, só digitar git pull no cmd, se não, usa o atualizar.py, se não, baixa o repositório dnv.

**Comment by Osdrix** [comment]
CMD:
[generic] master-pkg-t-1657904199000: Downloading webpage
[generic] master-pkg-t-1657904199000: Downloading m3u8 information
[generic] master-pkg-t-1657904199000: Checking m3u8 live status
[info] master-pkg-t-1657904199000: Downloading 1 format(s): 4118
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please install ffmpeg and add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 58
[download] Destination: C:\Katomart\katomart-master\Cursos\Programa Completo de Francês Ativo em 6 meses\12. Bônus Camila em Paris\1. Aula 1 Introdução\1. Aula.mp4
[download]   7.1% of ~ 197.72MiB at   12.89MiB/s ETA Unknown (frag 5/58)127.0.0.1 - - [02/Jul/2024 13:23:54] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:23:54] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:02] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:02] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:09] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:09] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/8)...
127.0.0.1 - - [02/Jul/2024 13:24:17] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:17] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:24] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:24] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (2/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (2/8)...
127.0.0.1 - - [02/Jul/2024 13:24:32] "GET /api/courses_progress HTTP/1.1" 200 -
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (2/8)...
127.0.0.1 - - [02/Jul/2024 13:24:32] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:39] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:40] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:48] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:48] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (3/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (3/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (3/8)...
127.0.0.1 - - [02/Jul/2024 13:24:54] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:24:55] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:25:03] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:25:03] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:25:09] "GET /api/courses_progress HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2024 13:25:09] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (4/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (4/8)...
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (4/8)...

**Comment by Osdrix** [comment]
[download] Got error: HTTP Error 504: Gateway Time-out. Retrying (7/8)...
[download] Got error: HTTP Error 504: Gateway Time-out. Retrying (8/8)...
127.0.0.1 - - [02/Jul/2024 16:01:54] "GET /api/courses_progress HTTP/1.1" 200 -
[download] Got error: HTTP Error 504: Gateway Time-out. Giving up after 8 retries
127.0.0.1 - - [02/Jul/2024 16:01:55] "GET /api/logs?perPage=15&page=1 HTTP/1.1" 200 -
[download] Got error: HTTPSConnectionPool(host='vod-akm.play.hotmart.com', port=443): Read timed out. (read timeout=20.0). Retrying (6/8)...

**Comment by katomaro** [comment]
Ele falhou um vídeo, os demais erros podem ou não ser o mesmo vídeo, em trechos diferentes, não sei dizer por causa do intervalo de 2 horas entre os comentários (8/8 foi a última tentativa no segmento, ele só desistiu lá em baixo). Consegue me dar detalhes da sua conexão?

**Comment by Osdrix** [comment]
300/300Mbs fiber - 1.1.1.1 DNS -- parece ser um fluxo de vídeos com detalhes "confidenciais", por isso não quer ser baixado.
