### ISSUE TITLE
[PEDIDO] Desmarcar tudo

### ISSUE THREAD

**Issue by mauroobento** [katomaro/katomart#48]
Estou usando o Kato aqui e, se eu entro para baixar as aulas de um determinado curso e  quero baixar um único módulo deste curso, preciso ficar clicando em box por box de cada módulo para desmarcar todas as caixas e deixar apenas a que eu quero. Teria como criar um box no topo, onde desmarca todos os checkbox de uma só vez e eu possa marcar apenas o que eu quiser?

**Comment by katomaro** [comment]
Erro da versão atual, inexistente na v2,

**Comment by mauroobento** [comment]
Não entendi... como assim ""erro da versão atual""? Só para entender mesmo... Porque isso é uma funcionalidade e não um bug ou algo..
