### ISSUE TITLE
Por favor, adicione a opção de seção colapsável na template de configurações

### ISSUE THREAD

**Issue by katomaro** [katomaro/katomart#5]
![image](https://github.com/katomaro/katomart/assets/53769456/e1e7fc39-60c4-4e9a-8246-4599150a98d7)  

O tipo de conteúdo irá incluir bem mais opções e o tipo de DRM também conforme tecnologias forem descobertas, estas seções devem ser colapsáveis para diminuir a quantidade de informações que o usuário tem na tela de uma vez.

**Comment by katomaro** [comment]
@felipe-adeildo

**Comment by felipe-adeildo** [comment]
O que você acha de, ao invés de ser um collapsible ser um modal, ao clicar, abre um modal?

**Comment by katomaro** [comment]
> O que você acha de, ao invés de ser um collapsible ser um modal, ao clicar, abre um modal?

Pode até ser, designer UX é você, do meu ponto de vista, colapsável fica mais legível ao usuário. Depende de como você for estilizar, se o pessoal achar ruim vc precisará alterar depois. Tenha em mente que terão outras seções de configurações adicionais.
