### ISSUE TITLE
ERRO AO INICIAR HOTMART

### ISSUE THREAD

**Issue by ramonmatias19** [katomaro/katomart#51]
![log](https://github.com/user-attachments/assets/1587aa2b-a69f-484f-a895-7626eb59d440)
Ao tentar iniciar a conta da hotmart, é retornardo um erro na api que seleciona a conta vide imagem em anexo para melhor auxilio, o que fazer?

**Comment by katomaro** [comment]
Plataforma alterando, como eu disse esse tempo todo atrás, que não valia a pena mexer. Uma correção está disponível apenas para sponsors até a próxima versão da aplicação até o fim deste mês, onde a nova corrigirá isso para todos e adicionará muitas funcionalidades. [Leia a página principal deste repositório.](https://github.com/katomaro/katomart?tab=readme-ov-file#deprecado-este-projeto-est%C3%A1-sendo-refatorado-do-zero-e-em-breve-o-c%C3%B3digo-aqui-ser%C3%A1-atualizado)
