### ISSUE TITLE
O nome dos cursos vem sem espaco e minúsculo!

### ISSUE THREAD

**Issue by sandepro00** [katomaro/katomart#53]
Bom dia!
Quando eu logo com uma conta "Hotmart" os nomes dos cursos ficam todos em minúsculo e sem espaço. 
EX: plagiadosidentidadevisual

onde o crreto seria:
COMUNIDADE PLAGIADOS POR DINAMITE CRIATIVA

![Screenshot_3](https://github.com/user-attachments/assets/cc2bf560-1667-4e11-88b5-d811444a6d9e)

obrigado desde já

**Comment by katomaro** [comment]
Isso é por causa que para capturar o nome dos produtos é necessário fazer uma requisição adicional, por isso, teria que usar o extra data nas configurações, o que pode ser perigoso se a conta tiver muitos produtos. Mas o comportamento foi normalizado na v2.

**Comment by sandepro00** [comment]
muito obrigado

Em ter., 6 de ago. de 2024 às 08:35, Victor Hugo Carvalho Dos Reis Santos <
***@***.***> escreveu:
