### ISSUE TITLE
Erro ao tentar iniciar conta Hotmart

### ISSUE THREAD

**Issue by CARR0000** [katomaro/katomart#54]
![edfaa0263afcc44f5a084928df0d10cd](https://github.com/user-attachments/assets/92d0eac9-9f95-4cad-b578-7e3fb3268b8e)

Não consigo iniciar a conta Hotmart

**Comment by Robinhor21** [comment]
Estou com msm erro =(

**Comment by HunterVSQ** [comment]
Também estou com o mesmo erro

**Comment by teuzinhoo1999** [comment]
Mesma coisa aqui, alguem conseguiu alguma solução?

**Comment by katomaro** [comment]
A hotmart mudou, eu estou atualizando a aplica;'ao como um todo, me dê entre 2 semanas a 1 mês para publicar à público. Contribuidores (35$ ou login que eu não possua) que solicitarem recebem versoes de teste (as vezes instáveis, mas trabalho junto com eles para cumprir seu objetivo imediato, sem perguntas feitas) antecipadamente.
