### ISSUE TITLE
ERRO ao acessar os CURSOS, retornando para aba CONTAS.

### ISSUE THREAD

**Issue by MJPNONE** [katomaro/katomart#59]
Bom dia, Katomaro.

Li em outros posts que este erro está sendo corrigido em uma versão futura, porém, como o último post tem mais de 1 mês e o erro persiste com os arquivos disponíveis para download na página do projeto, eu gostaria de saber se já foi disponibilizada uma versão corrigida e, caso positivo, onde posso encontrar o download?

De tudo que procurei na internet, esta foi a melhor ferramenta e a mais indicada para baixar videos da Hotmart. O projeto parace ser maravilhoso, parabéns. Se puder disponibilizá-lo para mim, eu agradeço, pois tenho cursos (que paguei caro) e gostaria de baixá-los.

O referido erro (para mim) foi o seguinte: 
![image](https://github.com/user-attachments/assets/c721fefa-0927-49fc-86b2-f6c034023f3d)

Agradeço e aguardo seu retorno.

**Comment by katomaro** [comment]
https://t.me/katomart
